config/routes.rb
Rails.application.routes.draw do

  get 'notifications/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users, only: [:index, :show]

  resources :blogs do
    resources :comments
    post :confirm, on: :collection
  end

  resources :relationships, only: [:create, :destroy]

  resources :contacts, only: [:new, :create] do
    collection do
      post :confirm
    end
  end

  resources :poems, only: [:index, :show]

  resources :conversations do
    resources :messages
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  root 'top#index'

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :comment
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!

  def index
    #@notifications = Notification.where(user_id: current_user.id).where(read: false).order(created_at: :desc)
    @notifications = Notification.where(user_id: current_user.id).where("read=false OR created_at > ?",Date.today-7).order(created_at: :desc)
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def posted_time(time)
    time > Date.today ? "#{time_ago_in_words(time)}前" : time.strftime('%m月%d日')
  end

  def read_status(read)
    read ? content_tag(:span,"既読",class:"blue") : content_tag(:span,"未読",class:"red")
  end
end

app/views/notifications/index.html.erb
<div class="container">
<div class="col-md-8 col-md-offset-2 col-sm-10">
<h2>今週のお知らせ</h2>

  <% @notifications.each do |notification| %>
  <hr>
    <div class="row">
      <div class="col-md-1 col-sm-1 left">
        <%= read_status(notification.read)%>
      </div>
      <div class="col-md-9 col-sm-9  left">
        <%= notification.comment.user.try(:name) %>さんが
        あなたのブログ（<%= link_to "#{notification.comment.blog.title}", blog_path(notification.comment.blog, notification_id: notification.id) %>）にコメントしました。
      </div>
      <div class="col-md-2 col-sm-2  left">
        <%= posted_time(notification.created_at) %></p>
      </div>
    </div>
  <% end %>

</div>
</div>